version: '3'

services:
  database:
    restart: always
    image: postgres:latest
    ports:
      - 5432:5432
    env_file:
      - database_creds.env
    volumes:
      - database-data:/var/lib/postgresql/data/

  python_api:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - database
    env_file:
      - database_creds.env
    ports:
      - 8080:8080

volumes:
  database-data:
    name: metaspace_database-data